# docker-compose.yml
version: '3.8'

services:
  ia1-strategist:
    build: ./ia1
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  ia2-dialog-agent:
    build: ./ia2
    environment:
      - BINGX_API_KEY=${BINGX_API_KEY}
      - BINGX_SECRET_KEY=${BINGX_SECRET_KEY}
      - IA1_URL=http://ia1-strategist:8000
    ports:
      - "8001:8000"
    depends_on:
      - ia1-strategist
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  monitoring:
    image: prometheus/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - monitoring